apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: my-terraform-app-2
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  source:
    repoURL: https://github.com/pabloisaacmauricio/tf-controller-helloworld.git
    targetRevision: HEAD

