apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-terraform-app-2
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/pabloisaacmauricio/tf-controller-helloworld.git
    targetRevision: HEAD

  destination: 
    server: https://kubernetes.default.svc
    namespace: another-namespace

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true